//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingSiteTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities
    {
        public Activities()
        {
            this.Bookings = new HashSet<Bookings>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int MaxPerson { get; set; }
        public int Duration { get; set; }
        public int CompanyId { get; set; }
        public string Time { get; set; }
        public int CityId { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Companies Companies { get; set; }
        public virtual ICollection<Bookings> Bookings { get; set; }
    }
}
