//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingSiteTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int Id { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public int PersonId { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual People People { get; set; }
    }
}
