// <auto-generated />
namespace BookingSiteTest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Newdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Newdata));
        
        string IMigrationMetadata.Id
        {
            get { return "201511221425498_New data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
