// <auto-generated />
namespace BookingSiteTest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _20151122 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20151122));
        
        string IMigrationMetadata.Id
        {
            get { return "201511221217384_2015-11-22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
