//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Activity = new HashSet<Activity>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AdministratorPersonId { get; set; }
        public bool HasAdministrator { get; set; }
    
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual Person Person { get; set; }
    }
}
